#!/usr/bin/env python3
"""
stack_check.py — analyse compiler-generated .su files for stack frame sizes.

Generated by GCC -fstack-usage (already present in s1.mk CFLAGS). Run after
'make build'; the .su files live next to each .o in the build tree.

Usage:
    python3 stack_check.py [BUILD_DIR] [--task-warn N] [--task-error N] [--top N]

.su file format:
    <file>:<line>:<col>:<function>TAB<bytes>TAB<qualifier>
    qualifier: static | dynamic | dynamic,bounded

Exit codes:
    0 — all task frames within limits (or no .su files found)
    1 — one or more task frames exceed --task-error threshold

Cortex-M33 (STM32H5xx) sizing guide
------------------------------------
  FreeRTOS context save on CM33:  ~68 B per task
  snprintf(%f) on double args:   ~400 B  ← CM33 has single-precision FPU only;
                                           all double arithmetic is soft-float via
                                           libgcc, far deeper than on Cortex-M7
  Typical call-chain overhead:   ~100 B
  Recommended safety margin:     ~128 B

  Peak estimate = frame + 68 + 400 (if snprintf float) + chain + 128

  Practical rule of thumb:
    task frame < 200 B  → safe for 512-B stack (without snprintf float)
    task frame < 400 B  → safe for 1024-B stack (without snprintf float)
    any task using snprintf(%f/%g) on a double → needs at least 1024-B stack
                                                  (1536 B recommended)
"""

import sys
import os
import glob
import re
import argparse

TASK_WARN_DEFAULT  = 200   # review carefully for 512-byte stacks
TASK_ERROR_DEFAULT = 400   # likely overflow with snprintf(double) on 1024-byte stack


def parse_su_files(build_dir):
    entries = []
    pattern = os.path.join(build_dir, "**", "*.su")
    for su_path in glob.glob(pattern, recursive=True):
        try:
            with open(su_path, encoding="utf-8", errors="replace") as f:
                for line in f:
                    line = line.rstrip()
                    if not line:
                        continue
                    m = re.match(r'^.+:\d+:\d+:(\w+)\t(\d+)\t(\S+)', line)
                    if m:
                        name      = m.group(1)
                        frame     = int(m.group(2))
                        qualifier = m.group(3)
                        norm      = su_path.replace("\\", "/")
                        parts     = norm.split("/")
                        short     = "/".join(parts[-2:]) if len(parts) >= 2 else norm
                        entries.append({
                            "name":      name,
                            "frame":     frame,
                            "qualifier": qualifier,
                            "path":      short,
                        })
        except OSError:
            pass
    return entries


def main():
    parser = argparse.ArgumentParser(
        description="Analyse GCC .su stack-frame sizes after 'make build'",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    parser.add_argument(
        "build_dir", nargs="?", default="build",
        help="Build directory containing .su files (default: build)")
    parser.add_argument(
        "--task-warn", type=int, default=TASK_WARN_DEFAULT,
        help=f"Warn when a *_task frame exceeds this many bytes (default: {TASK_WARN_DEFAULT})")
    parser.add_argument(
        "--task-error", type=int, default=TASK_ERROR_DEFAULT,
        help=f"Exit 1 when a *_task frame exceeds this many bytes (default: {TASK_ERROR_DEFAULT})")
    parser.add_argument(
        "--top", type=int, default=20,
        help="Number of largest functions to list (default: 20)")
    args = parser.parse_args()

    entries = parse_su_files(args.build_dir)
    if not entries:
        print(f"No .su files found under '{args.build_dir}'. Run 'make build' first.")
        sys.exit(0)

    entries.sort(key=lambda e: e["frame"], reverse=True)

    # ── Top N by frame size ────────────────────────────────────────────────────
    print(f"\n=== Top {args.top} functions by local stack frame ===")
    print(f"  {'Frame':>5}  {'Function':<38}  File")
    print("  " + "-" * 70)
    for e in entries[: args.top]:
        dyn = " [dyn]" if "dynamic" in e["qualifier"] else ""
        print(f"  {e['frame']:5d}  {e['name']:<38}  {e['path']}{dyn}")

    # ── Task functions ─────────────────────────────────────────────────────────
    tasks = [e for e in entries if e["name"].endswith("_task")]
    has_error = False

    if tasks:
        print(f"\n=== Task entry points (*_task) ===")
        print(f"  WARN threshold : >{args.task_warn} B  (review for 512-B stacks)")
        print(f"  ERROR threshold: >{args.task_error} B  (likely overflow with snprintf(double))")
        print(f"  Remember: add ~68 B (FreeRTOS context) + ~400 B (snprintf double on CM33)")
        print(f"            + call-chain depth to each frame to get peak usage.")
        print(f"  {'Frame':>5}  {'Status':<6}  Task")
        print("  " + "-" * 50)
        for e in tasks:
            if e["frame"] > args.task_error:
                status    = "ERROR"
                has_error = True
            elif e["frame"] > args.task_warn:
                status = "WARN"
            else:
                status = "ok"
            print(f"  {e['frame']:5d}  {status:<6}  {e['name']}")
    else:
        print("\n  No *_task functions found in build tree.")

    # ── Summary ────────────────────────────────────────────────────────────────
    print()
    if has_error:
        print("RESULT: FAIL — one or more task frames exceed the error threshold.")
        print("        Increase that task's stack_size in its osThreadAttr_t.")
        sys.exit(1)
    else:
        print("RESULT: PASS — all task frames within thresholds.")
        sys.exit(0)


if __name__ == "__main__":
    main()
